"use client";

import ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const COMPANY_NAME =process.env.NEXT_PUBLIC_COMPANY_NAME ?? "ARRC Rewards";
const COMPANY_WEBSITE =process.env.NEXT_PUBLIC_COMPANY_WEBSITE ?? "https://arrcrewards.com";

const loadImageAsBase64 = (src: string): Promise<string> =>
  new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.src = src;
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx?.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = reject;
  });

const getTodayDate = () =>
  new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
  });

export const exportSpendingPDF = async (
  categoryMap: Record<string, number>
) => {
  const doc = new jsPDF();
  const logoBase64 = await loadImageAsBase64("/images/logo.png");

  doc.addImage(logoBase64, "PNG", 14, 12, 14, 14);

  doc.setFontSize(15);
  doc.setTextColor(20);
  doc.text(COMPANY_NAME, 38, 18);

  doc.setFontSize(11);
  doc.setTextColor(90);
  doc.text("Spending Report", 14, 32);

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Generated on: ${getTodayDate()}`, 196, 32, { align: "right" });

  doc.setDrawColor(220);
  doc.line(14, 38, 196, 38);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();


  doc.saveGraphicsState?.();

  doc.setGState?.(new (doc as any).GState({ opacity: 0.06 }));

  doc.setFontSize(80);
  doc.setTextColor(160);
  doc.text("ARRC", pageWidth / 2, pageHeight / 2, {
    align: "center",
    angle: 45,
  });


  doc.restoreGraphicsState?.();

  const tableData = Object.entries(categoryMap).map(([category, amount]) => [
    category,
    `$${amount.toLocaleString("en-US", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`,
  ]);

  autoTable(doc, {
    startY: 44,
    head: [["Category", "Amount ($)"]],
    body: tableData,

    styles: {
      fontSize: 10,
      textColor: 55,
      valign: "middle",
      cellPadding: {
        top: 4,
        bottom: 4,
        left: 8,
        right: 8,
      },
    },

    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [250, 251, 252],
    },

    columnStyles: {
      0: {
        halign: "left",
        cellWidth: 145, 
      },
      1: {
        halign: "right",
        cellWidth: 35, 
        fontStyle: "bold",
      },
    },

    theme: "plain",
    margin: { left: 14, right: 14 },
  });

  const h = doc.internal.pageSize.height;

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(
    "This report is generated by ARRC Rewards for informational purposes only.",
    14,
    h - 18
  );

  doc.text("For more insights, visit", 14, h - 12);
  doc.setTextColor(30, 64, 175);
  doc.textWithLink(COMPANY_WEBSITE, 47, h - 12, {
    url: COMPANY_WEBSITE,
  });

  doc.save("spending-report.pdf");
};


export const exportSpendingExcel = async (
  categoryMap: Record<string, number>
) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Spending Report");

  worksheet.columns = [
    { key: "category", width: 50 }, 
    { key: "amount", width: 18 },
  ];

  worksheet.getRow(1).height = 42;
  worksheet.getRow(2).height = 22;

  const logoBase64 = await fetch("/images/logo.png")
    .then((r) => r.blob())
    .then(
      (b) =>
        new Promise<string>((res) => {
          const fr = new FileReader();
          fr.onloadend = () => res(fr.result as string);
          fr.readAsDataURL(b);
        })
    );

  const logoId = workbook.addImage({
    base64: logoBase64,
    extension: "png",
  });

  worksheet.addImage(logoId, {
    tl: { col: 0, row: 0 },
    ext: { width: 70, height: 70 },
  });

  worksheet.mergeCells("B1:D1");
  worksheet.getCell("B1").value = COMPANY_NAME;
  worksheet.getCell("B1").font = { size: 16, bold: true };
  worksheet.getCell("B1").alignment = { vertical: "middle" };

  worksheet.mergeCells("B2:D2");
  worksheet.getCell("B2").value = "Spending Report";
  worksheet.getCell("B2").font = { size: 11, color: { argb: "FF555555" } };

  worksheet.mergeCells("E2:F2");
  worksheet.getCell("E2").value = `Generated on: ${getTodayDate()}`;
  worksheet.getCell("E2").alignment = { horizontal: "right" };

  worksheet.addRow([]);

  const headerRow = worksheet.addRow(["Category", "Amount ($)"]);
  headerRow.height = 26;

  headerRow.eachCell((cell) => {
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF2563EB" },
    };
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
  });

  headerRow.getCell(2).alignment = { horizontal: "right" };


  Object.entries(categoryMap).forEach(([category, amount], index) => {
    const row = worksheet.addRow([category, amount]);
    row.height = 22;

    if (index % 2 === 0) {
      row.eachCell((cell) => {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFF7F8FA" },
        };
      });
    }

    row.getCell(2).numFmt = "$#,##0.00";
    row.getCell(2).alignment = { horizontal: "right" };
    row.getCell(2).font = { bold: true };
  });

  worksheet.addRow([]);
  worksheet.addRow([`Generated on: ${getTodayDate()}`]).font = { italic: true };

  worksheet.addRow([
    "This report is generated by ARRC Rewards for informational purposes only.",
  ]).font = { italic: true };

  const linkRow = worksheet.addRow([
    { text: COMPANY_WEBSITE, hyperlink: COMPANY_WEBSITE },
  ]);
  linkRow.font = { underline: true, color: { argb: "FF2563EB" } };

  const buffer = await workbook.xlsx.writeBuffer();
  saveAs(
    new Blob([buffer], {
      type:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }),
    "spending-report.xlsx"
  );
};
