"use client";

  const motivationalPhrases = [
    "Your thoughts shape your financial destiny.",
    "Wealth begins in the mind, then manifests in reality.",
    "Every great fortune started with a single decision.",
    "Your desire for wealth must be definite and persistent.",
    "Knowledge without action is merely philosophy.",
    "The person you become determines the wealth you attract.",
    "Financial success requires both planning and persistence.",
    "Your habits today create your fortune tomorrow.",
    "Wisdom is the foundation of all lasting wealth.",
    "A part of all you earn should be yours to keep.",
    "Make your gold work for you, not you for gold.",
    "The path to prosperity is paved with disciplined savings.",
    "Invest in your knowledge first, wealth will follow.",
    "Small daily deposits build massive wealth over time.",
    "Your financial future is created by today's choices.",
    "Compound growth rewards the patient investor.",
    "Wealth flows to those who prepare to receive it.",
    "Every dollar saved is a soldier in your wealth army.",
    "The best time to invest was yesterday, today is second best.",
    "Financial freedom begins with financial discipline.",
    "Your money should multiply while you sleep.",
    "Wise spending creates more than wise earning.",
    "A fool and their money are soon parted, wisdom keeps it.",
    "Let each dollar bring more dollars to serve you.",
    "The wealthy think differently about money and time.",
    "Prosperity consciousness attracts prosperity.",
    "Your net worth follows your self worth.",
    "Debt is a burden, investments are wings.",
    "Plan your spending, then spend your plan.",
    "Financial education is worth more than gold.",
    "The principles of wealth never change, only the faces.",
    "Consistency compounds into extraordinary results.",
    "Your financial goals must be written and reviewed daily.",
    "Wealth is attracted to those who respect it.",
    "Every investment is a vote for your future self.",
    "The road to riches is paved with smart choices.",
    "Your earning power is your greatest asset.",
    "Money multiplies for those who understand its laws.",
    "Financial success is 80% psychology, 20% mechanics.",
    "The wealthy focus on assets, not expenses.",
    "Your investment strategy reveals your financial maturity.",
    "Patience and persistence break through any resistance.",
    "Small amounts consistently invested create fortunes.",
    "The price of success is discipline and sacrifice.",
    "Your financial thermostat needs constant upgrading.",
    "Abundance is a mindset before it's a bank account.",
    "Every master was once a beginner with commitment.",
    "Your money story shapes your money reality.",
    "Invest in yourself first, the returns are guaranteed.",
    "Financial independence is freedom in its truest form.",
    "The wealthy see opportunities where others see obstacles.",
    "Your spending reveals your true priorities.",
    "Prosperity follows a prepared and focused mind.",
    "Every financial decision is a brick in your wealth house.",
    "The path to wealth is simple, but not easy.",
    "Your retirement is being funded by today's choices.",
    "Money is a tool, wisdom is knowing how to use it.",
    "The wealthy plant trees whose shade they'll never sit in.",
    "Your financial habits are your wealth blueprints.",
    "Delayed gratification creates lasting prosperity.",
    "The richest people have the longest time horizons.",
    "Your money mindset determines your money magnitude.",
    "Financial literacy is the gateway to financial liberty.",
    "Every dollar invested is a seed for future harvest.",
    "The power of compound interest is the eighth wonder.",
    "Your future security is built on present sacrifices.",
    "Wealth accumulation requires both earning and keeping.",
    "The financially wise live below their means always.",
    "Your investment portfolio reflects your life priorities.",
    "Money flows to those who give it purpose and direction.",
    "The successful focus on net worth, not appearances.",
    "Your earning ability is your most valuable resource.",
    "Financial wisdom turns small streams into mighty rivers.",
    "The path to prosperity starts with a single saved dollar.",
    "Your money works hardest when invested wisely.",
    "Wealth building is marathon training, not a sprint.",
    "The financially free focus on passive income streams.",
    "Your relationship with money needs constant nurturing.",
    "Every investment decision shapes your financial future.",
    "The wealthy understand the value of time and money.",
    "Your financial success mirrors your financial knowledge.",
    "Money multiplies for those who respect its power.",
    "The disciplined saver becomes the wealthy investor.",
    "Your spending habits reveal your financial future.",
    "Financial freedom is earned through consistent action.",
    "The price of financial success is paid in advance.",
    "Your investment strategy is your wealth roadmap.",
    "Money gravitates toward those who understand it.",
    "The financially wise balance today and tomorrow.",
    "Your net worth grows from self-improvement first.",
    "Every dollar saved is a step toward independence.",
    "The wealthy think in decades, not quarters.",
    "Your financial education never stops paying dividends.",
    "Money is multiplied by those who know its laws.",
    "The path to riches requires vision and persistence.",
    "Your daily habits determine your financial destination.",
    "Financial success is built on a foundation of learning.",
    "The wise investor plants seeds in all seasons.",
    "Your money mindset attracts your money reality.",
    "Every investment is a bet on your future self.",
    "The financially successful have clear written goals.",
    "Your wealth is measured by what you keep, not earn.",
    "Money management is self-management in disguise.",
    "The patient investor reaps the greatest rewards.",
    "Your financial philosophy shapes your financial reality.",
    "Every wise investment moves you closer to freedom.",
    "The road to wealth is traveled by the disciplined.",
    "Your retirement lifestyle is funded by today's choices.",
    "Financial wisdom transforms pennies into fortunes.",
    "The wealthy see money as a multiplying tool.",
    "Your spending plan is your wealth creation system.",
    "Every dollar directed wisely builds lasting security."
  ];

export default motivationalPhrases;